// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelLibrary;

#nullable disable

namespace ModelLibrary.Migrations
{
    [DbContext(typeof(CodeFirstDbContext))]
    [Migration("20230922114537_Intinal2")]
    partial class Intinal2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelLibrary.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "Ngô Văn Lợi"
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "Hoàng Văng Tấn"
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Đào Hải Nam"
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "Trần Thị Huyền"
                        },
                        new
                        {
                            CustomerId = 5,
                            Name = "Nguyễn Văn Lực"
                        });
                });

            modelBuilder.Entity("ModelLibrary.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreatedDate = "2023 - 07 - 01",
                            CustomerId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CreatedDate = "2023 - 07 - 01",
                            CustomerId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            OrderId = 3,
                            CreatedDate = "2023 - 07 - 01",
                            CustomerId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            OrderId = 4,
                            CreatedDate = "2023 - 06 - 30",
                            CustomerId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            OrderId = 5,
                            CreatedDate = "2023 - 06 - 30",
                            CustomerId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            OrderId = 6,
                            CreatedDate = "2023 - 06 - 30",
                            CustomerId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("ModelLibrary.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Laptop MSI 2022",
                            Price = 3000.0,
                            Quantity = 200
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Laptop ACER 2023",
                            Price = 2500.0,
                            Quantity = 220
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Laptop ASUS 2022",
                            Price = 2700.0,
                            Quantity = 220
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Laptop DELL 2022",
                            Price = 3900.0,
                            Quantity = 220
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Laptop HP 2021",
                            Price = 1900.0,
                            Quantity = 220
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Laptop MSI 2023",
                            Price = 4000.0,
                            Quantity = 220
                        });
                });

            modelBuilder.Entity("ModelLibrary.Order", b =>
                {
                    b.HasOne("ModelLibrary.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLibrary.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ModelLibrary.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ModelLibrary.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
